export type { ServiceProvider } from './ServiceProvider.js';
export { CategoryRegistry } from './category/CategoryRegistry.js';
export { useActiveCategory, useActiveCategoryStore } from './category/useActiveCategory.js';
export { useCategoryList } from './category/useCategoryList.js';
export { useCategorySearchFields } from './category/useCategorySearchFields.js';
export { SongDuplicateDetector } from './duplicate/SongDuplicateDetector.js';
export { FilterEngine } from './search/FilterEngine.js';
export type { FilterResult } from './search/FilterEngine.js';
export { SortEngine } from './search/SortEngine.js';
export type { SortResult } from './search/SortEngine.js';
